spring:
  application:
    name: search

  data:
    redis:
      host: localhost
      port: 6379
    elasticsearch:
      repositories:
        enabled: true
      url: localhost:9200

version: 1.0.0