spring:
  application:
    name: search

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/search?useSSL=false&serverTimezone=UTC
    username: root
    password: root

version: 1.0.0